export const PUBLIC_PORT = Number.parseInt(process.env.PORT ?? "8080", 10);

export const INTERNAL_HERMES_API_PORT = Number.parseInt(
  process.env.INTERNAL_HERMES_API_PORT ?? "8642",
  10,
);
export const INTERNAL_TEAMS_PORT = Number.parseInt(process.env.INTERNAL_TEAMS_PORT ?? "3978", 10);
export const INTERNAL_TELEGRAM_WEBHOOK_PORT = Number.parseInt(
  process.env.INTERNAL_TELEGRAM_WEBHOOK_PORT ?? "8443",
  10,
);
export const INTERNAL_WEBHOOK_PORT = Number.parseInt(process.env.INTERNAL_WEBHOOK_PORT ?? "8644", 10);

export const INTERNAL_HOST = "127.0.0.1";
export const HERMES_API_TARGET = `http://${INTERNAL_HOST}:${INTERNAL_HERMES_API_PORT}`;
export const HERMES_HOME = (process.env.HERMES_HOME ?? "/data/hermes").trim();

/** Keys persisted in HERMES_HOME/.env */
export const MANAGED_ENV_KEYS = [
  "CUSTOM_ENDPOINT_URL",
  "CUSTOM_ENDPOINT_API_KEY",
  "NVIDIA_NIM_API_KEY",
  "MISTRAL_API_KEY",
  "GITHUB_TOKEN",
  "GROQ_API_KEY",
  "OPENROUTER_API_KEY",
  "COHERE_API_KEY",
  "CEREBRAS_API_KEY",
  "HUGGINGFACE_API_KEY",
  "NIM_BASE_URL",
  "MISTRAL_BASE_URL",
  "GITHUB_BASE_URL",
  "GROQ_BASE_URL",
  "OPENROUTER_BASE_URL",
  "COHERE_BASE_URL",
  "CEREBRAS_BASE_URL",
  "HF_BASE_URL",
  "HERMES_MODEL",
  "TELEGRAM_BOT_TOKEN",
  "TELEGRAM_ALLOWED_USERS",
  "TELEGRAM_HOME_CHANNEL",
  "TELEGRAM_HOME_CHANNEL_NAME",
  "TELEGRAM_HOME_CHANNEL_THREAD_ID",
  "TELEGRAM_WEBHOOK_URL",
  "TELEGRAM_WEBHOOK_SECRET",
  "TELEGRAM_REQUIRE_MENTION",
  "DISCORD_BOT_TOKEN",
  "DISCORD_ALLOWED_USERS",
  "SLACK_BOT_TOKEN",
  "SLACK_APP_TOKEN",
  "SLACK_ALLOWED_USERS",
  "TEAMS_CLIENT_ID",
  "TEAMS_CLIENT_SECRET",
  "TEAMS_TENANT_ID",
  "TEAMS_ALLOWED_USERS",
  "TEAMS_ALLOW_ALL_USERS",
  "TEAMS_HOME_CHANNEL",
  "TEAMS_HOME_CHANNEL_NAME",
  "API_SERVER_KEY",
  "GATEWAY_ALLOW_ALL_USERS",
  "API_SERVER_CORS_ORIGINS",
  "API_SERVER_MODEL_NAME",
  "WEBHOOK_ENABLED",
  "WEBHOOK_SECRET",
];

export const SECRET_KEYS = new Set([
  "CUSTOM_ENDPOINT_API_KEY",
  "NVIDIA_NIM_API_KEY",
  "MISTRAL_API_KEY",
  "GITHUB_TOKEN",
  "GROQ_API_KEY",
  "OPENROUTER_API_KEY",
  "COHERE_API_KEY",
  "CEREBRAS_API_KEY",
  "HUGGINGFACE_API_KEY",
  "API_SERVER_KEY",
  "TELEGRAM_BOT_TOKEN",
  "TELEGRAM_WEBHOOK_SECRET",
  "DISCORD_BOT_TOKEN",
  "SLACK_BOT_TOKEN",
  "SLACK_APP_TOKEN",
  "TEAMS_CLIENT_SECRET",
  "WEBHOOK_SECRET",
]);

/** UI-only key mapped to config.yaml model.default */
export const CONFIG_MODEL_KEY = "MODEL_DEFAULT";
export const CONFIG_PROVIDER_KEY = "MODEL_PROVIDER";
export const CONFIG_BASE_URL_KEY = "MODEL_BASE_URL";
export const CONFIG_API_KEY_KEY = "MODEL_API_KEY";

/** At least one required for a working agent */
export const LLM_PROVIDER_KEYS = [
  "CUSTOM_ENDPOINT_URL",
  "NVIDIA_NIM_API_KEY",
  "MISTRAL_API_KEY",
  "GITHUB_TOKEN",
  "GROQ_API_KEY",
  "OPENROUTER_API_KEY",
  "COHERE_API_KEY",
  "CEREBRAS_API_KEY",
  "HUGGINGFACE_API_KEY",
];

/** Fields marked with a red asterisk in the setup UI (default Telegram path) */
export const UI_REQUIRED_FIELDS = new Set([
  CONFIG_API_KEY_KEY,
  CONFIG_MODEL_KEY,
  "TELEGRAM_BOT_TOKEN",
  "TELEGRAM_ALLOWED_USERS",
]);

export const PLATFORM_CHECKS = [
  { id: "telegram", label: "Telegram", keys: ["TELEGRAM_BOT_TOKEN"] },
  { id: "discord", label: "Discord", keys: ["DISCORD_BOT_TOKEN"] },
  { id: "slack", label: "Slack", keys: ["SLACK_BOT_TOKEN", "SLACK_APP_TOKEN"] },
  {
    id: "teams",
    label: "Teams",
    keys: ["TEAMS_CLIENT_ID", "TEAMS_CLIENT_SECRET", "TEAMS_TENANT_ID"],
  },
];
